apiVersion: v2
name: kloudlite-platform
description: Helm Chart for installing and setting up kloudlite platform on your own hosted Kubernetes clusters.

type: application

version: 1.0.5-nightly

appVersion: "1.0.5-nightly"

dependencies:
  - name: redpanda-operator
    version: 22.1.6
    repository: https://charts.vectorized.io

  - name: ingress-nginx
    version: 4.6.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.install

  - name: cert-manager
    version: v1.11.0
    repository: https://charts.jetstack.io
    condition: cert-manager.install

  - name: vector
    version: 0.23.0
    repository: https://helm.vector.dev
    condition: vector.install

  - name: kube-prometheus
    version: 8.15.1
    repository: https://charts.bitnami.com/bitnami
    condition: kube-prometheus.install

  - name: grafana
    version: 9.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: grafana.install
