name: Readme Generator

on: push
jobs:
  generate-readmes:
    container: ghcr.io/kloudlite/kloudlite-helm-charts-builder:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - |+
        for item in "$(ls charts/)"
        do
          pushd charts/$item
          task compile
          popd
        done

      - task generate-chart-docs

