name: Readme Generator
on: push

jobs:
  generate-readmes:
    runs-on: ubuntu-latest
    container: ghcr.io/kloudlite/kloudlite-helm-charts-builder:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: generate values.yaml from values.yml.tpl
        run: |+
          for item in `ls charts/`
          do
            pushd charts/$item
            task compile
            popd
          done

      - name: generate chart docs
        run: task generate-chart-docs

