name: Readme Generator
on: push

jobs:
  generate-readmes:
    runs-on: ubuntu-latest
    container: ghcr.io/kloudlite/kloudlite-helm-charts-builder:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Configure Git
      #   shell: bash
      #   run: |
      #     echo "current working directory: $PWD"
      #     ls -al
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: generate values.yaml from values.yml.tpl
        shell: bash
        run: |+
          for item in `ls charts/`
          do
            pushd charts/$item
            task compile
            popd
          done

      - name: generate chart docs
        shell: bash
        run: task generate-chart-docs

      - name: commit all of the changes
        shell: bash
        run: |+
          git config --global --add safe.directory /__w/kloudlite-helm-charts/kloudlite-helm-charts
          git status -s
          git add .
          git commit -m "[workflow: readme-generator] generated README, and possibly updated values.yaml file from values.yml.tpl in individual charts"
          git push
